services:
  frontend:
    build: ./client
    ports:
    - "5173:5173"
    networks:
    - book-store

  backend:
    build: ./server
    ports:
    - "3000:3000"
    networks:
    - book-store
    depends_on:
    - mongodb

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    networks:
    - book-store

networks:
    book-store:
      driver: bridge

volumes:
    mongodb_data:
      driver: local